baseURL: https://vollkorntomate.de/
title: 'vollkorntomate'
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
theme: coder

enableGitInfo: true

languages:
  en:
    info: 'Student, Software Developer & more'
    languageName: EN
    weight: 1
    contentDir: "content/en"
    menu:
      main:
        # - name: 'Blog'
        #   weight: -110
        #   identifier: 'blog'
        #   url: '/blog/'
        - name: 'About me'
          weight: -100
          identifier: 'about'
          url: '/about/'
  de:
    info: 'Student, Softwareentwickler & mehr'
    languageName: DE
    weight: 2
    contentDir: "content/de"
    menu:
      main:
        # - name: 'Blog'
        #   weight: -110
        #   identifier: 'blog'
        #   url: '/blog/'
        - name: 'Über mich'
          weight: -100
          identifier: 'about'
          url: '/about/'



params:
  author: 'vollkorntomate'
  avatarurl: 'images/vollkorntomate.jpg'
  images: ['images/vollkorntomate.jpg']

  colorScheme: auto
  hidecolorschemetoggle: true

  favicon_16: 'images/favicon-16x16.png'
  favicon_32: 'images/favicon-32x32.png'

  social:
    - name: GitHub
      icon: fa fa-github fa-2x
      weight: 1
      url: 'https://github.com/vollkorntomate/'
    - name: GitLab
      icon: fa fa-gitlab fa-2x
      weight: 2
      url: 'https://gitlab.com/vollkorntomate/'
    - name: StackOverflow
      icon: fa fa-stack-overflow fa-2x
      weight: 3
      url: 'https://stackoverflow.com/vollkorntomate'
    - name: Twitter
      icon: fa fa-twitter fa-2x
      weight: 4
      url: 'https://twitter.com/vollkorntomate/'
    - name: Mastodon
      icon: fa fa-mastodon fa-2x
      weight: 5
      url: 'https://mastodon.social/@vollkorntomate'
    - name: Matrix
      icon: fa fa-matrix-org fa-2x
      weight: 6
      url: 'https://matrix.to/#/@t:vollkorntomate.de'